### ISSUE TITLE
Support long strings in Scala.js

### ISSUE THREAD

**Issue by rpiaggio** [suzaku-io/boopickle#79]
When decoding a large string in Scala.js an exception is thrown `RangeError: Maximum call stack size exceeded`.

**Comment by ochrons** [comment]
This is due to https://github.com/suzaku-io/boopickle/blob/864e89a51954491f3fc1754f0dfbe2c76dfaba1c/boopickle/js/src/main/scala/boopickle/StringCodec.scala#L187 passing the full character array to the function and browser JS engine not liking too long argument lists.

The solution is to break decoding of long strings into smaller parts and join the resulting strings later.
